### ISSUE TITLE
tq_exchange timeout issue

### ISSUE THREAD

**Issue by mcfsalla** [business-science/tidyquant#180] opened 2020-08-13 20:16 UTC
I am getting a timeout issue when using tq_exchange. It seems there is a problem when connecting to the exchange. Is there a way to fix this? (It seems that the old.nasdaq website is going to be retired, maybe that is the problem)

**Comment by mdancho84** [comment] 2020-08-13 20:22
Duplicate of #177 - Yes, old.nasdaq.com is being retired. Going through options now.

**Closed by mdancho84** 2020-08-13 20:22 UTC
