### ISSUE TITLE
tq_get(x, get="dividends") doesn't work

### ISSUE THREAD

**Issue by BeckyHan** [business-science/tidyquant#150] opened 2020-02-04 22:53 UTC
Hello Sir/Madam,

Recently I use tq_get(x, get="dividends"), I will get an error. And I tried multiple times, I cannot run it.

The error is:
"Warning message:
x = 'KO', get = 'dividends': Error in vapply(parse(text = fr[, 2]), eval, numeric(1)): values must be length 1,
 but FUN(X[[1]]) result is length 2".

Thank you.

**Comment by waynelapierre** [comment] 2020-02-11 19:31
I can replicate this issue on both Linux and windows.

**Comment by ecitera** [comment] 2020-02-14 00:10
I have the same problem with "AAPL" and "AMZN". However if I run `tq_index('SP500') %>% tq_get(get = 'dividends', from = '1950-01-01', to = Sys.Date())` it works, even though I only get dividends for 86 companies, among which "AAPL" and "AMZN" are not included. This is also weird...

Is anyone else having the same problem?

**Comment by pawelsobala** [comment] 2020-02-15 10:24
I confirm that the problem is there. Actually, the problem also involves getting the splits for stocks.

tq_get("GE", get="splits", from="1900-01-01") returns the same error.

The data on yahoo finance is present: https://finance.yahoo.com/quote/GE/history?period1=-252374400&period2=1581724800&interval=div%7Csplit&filter=split&frequency=1d

**Comment by ecitera** [comment] 2020-03-06 17:22
Hi guys, any leads on the problem we are having with dividends and splits? Data on Yahoo Finance are available for individual companies, like Apple: [](https://finance.yahoo.com/quote/AAPL/history?period1=345427200&period2=1583452800&interval=div%7Csplit&filter=div&frequency=1d)

**Comment by mdancho84** [comment] 2020-03-06 17:53
I have removed this functionality in favor of Tiingo. Use tq_get(get = “tiingo”). You will need to set up an API key which is free.

**Comment by kaybenleroll** [comment] 2020-03-10 21:11
It looks like this functionality has been fixed in the latest version of quantmod, so could possible be re-enabled in tidyquant?

**Comment by mdancho84** [comment] 2020-03-10 21:13
If it's indeed working, I will roll it out in 1.1.0

**Comment by mdancho84** [comment] 2020-03-11 12:02
Yahoo dividends and splits should work now. Use the development version of tidyquant. Use `tq_get("AAPL", get = "dividends")`. Splits uses `get = "splits"`.

**Comment by mdancho84** [comment] 2020-03-11 12:21
Closing - let me know if you have any further issues & I can reopen if needed.

**Closed by mdancho84** 2020-03-11 12:21 UTC

**Comment by ecitera** [comment] 2020-03-11 15:06
Now the function is working! I was able to get all the dividends of the companies in the SP500. Thanks a lot @mdancho84 !!

**Comment by mdancho84** [comment] 2020-03-11 15:10
Wonderful!
