### ISSUE TITLE
tq_exchange is not working

### ISSUE THREAD

**Issue by watermantle** [business-science/tidyquant#184] opened 2020-09-24 15:35 UTC
Hello,

I used tq_exchange to fetch exchange data, but it is not working as usual. After some inspections, I noticed that old.nasdaq.com might update its firewall to block the function's request. I tried faked headers with GET() function but it also failed. The weird thing is that the request has passed in Python with a faked headers.

Do you have any idea about the issue? Thank you!

**Comment by mdancho84** [comment] 2020-09-24 15:37
Looks like this is a duplicate of Issue #177 - Please use the development version of the package, which has the fix. 
https://github.com/business-science/tidyquant/issues/177

**Comment by watermantle** [comment] 2020-09-24 15:43
> Looks like this is a duplicate of Issue #177 - Please use the development version of the package, which has the fix.
> #177

Thank you so much!

**Closed** 2020-09-24 19:26 UTC
