### ISSUE TITLE
Problem with tq_exchange()

### ISSUE THREAD

**Issue by lynnaevans** [business-science/tidyquant#183] opened 2020-09-11 20:55 UTC
Hi

Getting the following on any of the three exchange options:

Getting data...

Warning messages:
1: In download.file(url, destfile = tmp, quiet = TRUE) :
  InternetOpenUrl failed: 'The operation timed out'
2: In value[[3L]](cond) : Error at nyse during call to tq_exchange.

Any thoughts?

Lynn

**Comment by mdancho84** [comment] 2020-09-11 20:56
duplicate of #177 - Fix is install the development version.

**Comment by lynnaevans** [comment] 2020-09-11 23:02
Thanks Matt for the super-fast response. NYSE works now. If there is a next time I will try to do better Google searches. :>)

**Closed** 2020-09-11 23:04 UTC
